# Piccolo Template Configuration
#
# This is the main configuration file for the Piccolo template. It is here where you can customize everything about your instance of a Piccolo website.
#

defaults: &defaults

  # General Site Information
  sitename: Challenged Children Foundtation Intl.
  site_description: Example Event is an event at Example University founded to raise money for Example Charity.
  url_to_site: "https://www.challengedchildren.org/"

  # University Information
  university: Example University
  univeristy_url: www.exampleuniversity.com
  university_location: Example City, EX

  # Donation Information
  charity_name: Example Charity
  donation_tagline: Support our participants

  # Donation Email
  donation_email_text: I have pledged to participate in the Example Event. This event benefits the Example Charity, which supports xx research. It is the largest student philanthropy event at Example University. I would be honored if you could donate to my campaign.

  # Event Information
  datetime_of_event: 120349563
  registration_fee_amount: 20
  location_of_event: Example Location
  about_event: Example Event was started in 2015 to support the Brian Piccolo Cancer Research foundation. (ect ect ect)

  # Event Participants (dancers, runners, ect.)
  participant_type: donator

  # Emails
  donation_message: Donate to our event!

  # Contact Information
  address_line_1: Cape Coast, Central Region, Ghana
  address_line_2: 5.118718, -1.267285 
  city: PO Box 1064
  state: 
  zip_code: 
  email: ccfoundationintl@gmail.com
  phone: 
  twitter: http://www.example.twitter.com
  facebook: https://www.facebook.com/challengedchildren/
  instagram: http://www.instagram.com/example
  youtube: http://www.youtube.com/example

development:
  <<: *defaults

production:
  <<: *defaults

test:
  <<: *defaults
