# Piccolo Template Configuration
#
# This is the main configuration file for the Piccolo template. It is here where you can customize everything about your instance of a Piccolo website.
#

defaults: &defaults

  # General Site Information
  sitename: "Hit The Bricks: DC"
  site_description: "Hit The Bricks: DC is a social fun-run designed to bring our Wake Forest community together in support of a cause near and dear to all of our hearts."
  url_to_site: "http://www.dchitthebricks.com"

  # University Information
  university: Wake Forest University
  univeristy_url: www.wfu.edu
  university_location: Winston Salemn, NC

  # Donation Information
  charity_name: Brian Piccolo Cancer Research Fund
  donation_tagline: Support our runners

  # Donation Email
  donation_email_text: "I have pledged to participate in Hit The Bricks: DC. This event benefits the Example Charity, which supports xx research. It is the largest student philanthropy event at Example University. I would be honored if you could donate to my campaign."

  # Event Information
  datetime_of_event: 120349563
  registration_fee_amount: 20
  location_of_event: National Mall, Washington, DC
  about_event: "The Brian Piccolo Cancer Drive was established by students in 1980 in memory of Brian Piccolo, a great Wake Forest athlete/alum and Chicago Bears football star who died of cancer. For the past 34 years, Wake Forest students, alumni, and friends have planned and participated in various events to raise funds for cancer research at the Wake Forest Baptist Medical Center’s Comprehensive Cancer Center. The Fund has raised more than $1,750,000 for the WFU Cancer Center! <br><br> Hit The Bricks was started on campus in 2003. Each year, hundreds of students have gathered on Hearn Plaza to take turns running laps around the Quad.  We are bringing the tradition to the Nation’s Capital – with a few alterations. <br><br> Hit The Bricks: DC is a social fun-run designed to bring our Wake Forest community together in support of a cause near and dear to all of our hearts."

  # Event Participants (dancers, runners, ect.)
  participant_type: runner

  # Emails
  donation_message: "Donate to Hit The Bricks: DC!"

  # Contact Information
  address_line_1: c/o Pro Humanitate Institute 
  address_line_2: Campus Box 7526 
  city: Winston-Salem
  state: NC
  zip_code: 27109
  email: dchitthebricks@gmail.com
  phone: (336) 758-5000
  twitter: http://www.dchitthebricks.twitter.com
  facebook: http://www.facebook.com/dchitthebricks
  instagram: http://www.instagram.com/dchitthebricks
  youtube: http://www.youtube.com/dchitthebricks

development:
  <<: *defaults

production:
  <<: *defaults

test:
  <<: *defaults
