# Piccolo Template Configuration
#
# This is the main configuration file for the Piccolo template. It is here where you can customize everything about your instance of a Piccolo website.
#

defaults: &defaults

  # General Site Information
  sitename: "Hit The Bricks: DC"
  site_description: "Hit The Bricks: DC is a social fun-run designed to bring our Wake Forest community together to raise money and support for the Brian Piccolo Cancer Research Fund and the Wake Forest Cancer Center."
  url_to_site: "http://www.dchitthebricks.com"

  # University Information
  university: Wake Forest University
  univeristy_url: www.wfu.edu
  university_location: Winston Salemn, NC

  # Donation Information
  charity_name: Brian Piccolo Cancer Research Fund
  donation_tagline: Support our runners

  # Donation Email
  donation_email_text: "Since 2003, Wake Forest students and faculty have gathered on Hearn Plaza, running laps around the quad to raise money for the Brian Piccolo Cancer Research Fund.  Hit The Bricks is the largest student-run philanthropy event on campus and has become a beloved cornerstone tradition at Wake Forest.  The event brings together the entire campus community, as hundreds of students pledge to stay on their feet for twelve hours in honor and in memory of those who have battled cancer.  This year we are bringing Hit The Bricks to the Nation's Capital.<br><br>I have pledged to participate in Hit The Bricks: DC on October 1, 2016. Though I won't be running for twelve hours, I will be completing laps on the National Mall with fellow alumni, friends and family.  This event directly benefits the Brian Piccolo Cancer Research Fund, which supports innovative research at the Comprehensive Cancer Center at Wake Forest Baptist Medical Center. Since it was founded in 1980, the Brian Piccolo Cancer Research Fund has raised over $1.7 million through the efforts of our generous sponsors and dedicated donors.<br><br>I am hoping that you will consider making a contribution on my behalf for this event.  All donations are secure, easy, and tax-deductible. With your help, we are one step closer to our goal of raising over $200,000! "

  # Event Information
  datetime_of_event: 120349563
  registration_fee_amount: 20
  location_of_event: National Mall, Washington, DC
  about_event: "Since 2003, Wake Forest students and faculty have gathered on Hearn Plaza, running laps around the quad to raise money for the Brian Piccolo Cancer Research Fund.  Hit The Bricks is the largest student-run philanthropy event on campus and has become a beloved cornerstone tradition at Wake Forest.  The event brings together the entire campus community, as hundreds of students and faculty pledge to stay on their feet for twelve hours in honor and in memory of those who have battled cancer.  This year we are bringing Hit The Bricks to the Nation's Capital!<br><br>The Brian Piccolo Cancer Drive was established by students in 1980 in memory of Brian Piccolo, a great Wake Forest athlete/alum and Chicago Bears football star who died of cancer. For the past 34 years, Wake Forest students, alumni, and friends have planned and participated in various events to raise funds for cancer research at the Wake Forest Baptist Medical Center’s Comprehensive Cancer Center. The Fund has raised more than $1,750,000 for the WFU Cancer Center."

  # Event Participants (dancers, runners, ect.)
  participant_type: runner

  # Emails
  donation_message: "Donate to Hit The Bricks: DC!"

  # Contact Information
  address_line_1: c/o Pro Humanitate Institute 
  address_line_2: Campus Box 7526 
  city: Winston-Salem
  state: NC
  zip_code: 27109
  email: dchitthebricks@gmail.com
  phone: (336) 758-5000
  twitter: http://www.dchitthebricks.twitter.com
  facebook: http://www.facebook.com/dchitthebricks
  instagram: http://www.instagram.com/dchitthebricks
  youtube: http://www.youtube.com/dchitthebricks

development:
  <<: *defaults

production:
  <<: *defaults

test:
  <<: *defaults
