# Piccolo Template Configuration
#
# This is the main configuration file for the Piccolo template. It is here where you can customize everything about your instance of a Piccolo website.
#

# General Site Information
sitename: Example Event
site_description: Example Event is an event at Example University founded to raise money for Example Charity.

# University Information
university: Example University
univeristy_url: www.exampleuniversity.com
university_location: Example City, EX

# Donation Information
charity_name: Example Charity

# Event Information
datetime_of_event: 120349563
location_of_event: Example Location

